config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations', passwords: 'passwords'}
  root 'grams#index'
  resources :grams do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gram
  belongs_to :user
  validates :message, presence:true, length: { maximum: 100, minimum: 5 }
end

app/models/gram.rb
class Gram < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :message, presence:true, length: { maximum: 100, minimum: 5 }
  validates :image, presence:true

  mount_uploader :image, ImageUploader

  def next_gram
    @gram = Gram.where('id > ?', id).first
  end

  def previous_gram
    @gram = Gram.where('id < ?', id).last
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :grams
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  helper_method :resource_name, :resource, :devise_mapping, :resource_class

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def render_not_found(status=:not_found)
    render plain: "#{status.to_s.titleize} … o.O", status: status
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController  
  before_action :authenticate_user!, only: [:create]

  def create
    @gram = Gram.find_by_id(params[:gram_id])
    return render_not_found if @gram.blank?
    @gram.comments.create(comment_params.merge(user: current_user))
    if @gram.invalid?
      flash[:alert] = 'Comment must be between 5-100 characters'
    end
    redirect_to gram_path(@gram)
  end

  private

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/grams_controller.rb
class GramsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @grams = Gram.all.order(updated_at: :desc)
  end

  def new
    @gram = Gram.new
  end

  def create
    @gram = current_user.grams.create(gram_params)
    if @gram.invalid?
      flash[:alert] = 'Post must include a 5-100 character message & an image'
    end
    redirect_to root_path
  end

  def show
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
  end

  def edit
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user
  end

  def update
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user
    @gram.update_attributes(gram_params)
    if @gram.valid?
      redirect_to gram_path(@gram)
    else
      return render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user
    @gram.destroy
    redirect_to root_path
  end

  private

  def gram_params
    params.require(:gram).permit(:message, :image)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with resource, location: after_sending_reset_password_instructions_path_for(resource_name)
    else
      response_to_password_reset_failure resource    
    end
  end

  private

  def after_sending_reset_password_instructions_path_for(resource_name)
    root_path
  end
  
  def response_to_password_reset_failure(resource)
    redirect_back fallback_location: root_path, alert: "Please check email"
  end
end


app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController  
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      response_to_sign_up_failure resource    
    end
  end

  private

  def response_to_sign_up_failure(resource)
    if resource.email == "" && resource.password == nil
      redirect_back fallback_location: root_path, alert: "Please check that all form fields are filled"
    elsif User.pluck(:email).include? resource.email
      redirect_back fallback_location: root_path, alert: "Email already exists"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/views/grams/edit.html.erb
<div class="u-form">
  <%= simple_form_for @gram do |f| %>
    <%= f.input :message, required: true, label: false, input_html: {maxlength: 100} %>
    <%= f.input_field :image, class: 'u-enter float-left' %>
    <%= f.submit 'Update Post', class: 'u-enter float-right' %>
  <% end %>
</div>

app/views/grams/index.html.erb
<% @grams.each do |gram| %>
  <%= link_to gram_path(gram) do %>
    <div class="u-post">
      <div class="u-image" style="background-image: url(<%= gram.image.url %>)"></div>
      <div class="u-message">
        <span class="fa fa-user-circle" style="font-size:20px;"></span> # <%= gram.user_id %> … <%= gram.message %>
      </div>
    </div>
  <% end %>
<% end %>
 
 
 

app/views/grams/new.html.erb
<div class="u-form">
  <%= simple_form_for Gram.new do |f| %>
    <%= f.input :message, required: true, label: false, placeholder: 'Post must include a 5-100 character message & an image', input_html: {maxlength: 100} %>
    <%= f.input_field :image, class: 'u-enter float-left' %>
    <%= f.submit 'Add Post', class: 'u-enter float-right' %>
  <% end %>
</div>

app/views/grams/show.html.erb
<!-- post -->
  <div class="u-post">
    <div id="u-show<%= @gram.id %>" class="u-image u-show" style="background-image: url(<%= @gram.image.url %>)"></div>
    <div class="u-message">
      <span class="fa fa-user-circle" style="font-size:20px;"></span> # <%= @gram.user_id %> … <%= @gram.message %>
    </div>
  </div>

<!-- next -->
  <% if @gram.next_gram.present? %>
    <div class="u-next">
      <%= link_to gram_path(@gram.next_gram) do %>
        <span class="fa fa-arrow-right" style="font-size:24px;"></span>
      <% end %>
      <span class="u-text">next</span>
    </div>
  <% end %>

<!-- previous -->
  <% if @gram.previous_gram.present? %>
    <div class="u-previous">  
      <%= link_to gram_path(@gram.previous_gram) do %>
        <span class="fa fa-arrow-left" style="font-size:24px;"></span>
        <% end %>
      <span class="u-text">previous</span>
    </div>
  <% end %>

<!-- comments -->
  <div class="u-comment">
    <div id="AddComment" class="u-form">
      <%= simple_form_for Comment.new, url: gram_comments_path(@gram) do |f| %>
        <%= f.input :message, required: true, label: false, placeholder: 'Comment must be between 5-100 characters', input_html: {maxlength: 100} %>
        <%= f.submit 'Add Comment', class: 'u-enter' %>
      <% end %>
    </div>
    <div class="u-user-comments">
      <% @gram.comments.order(created_at: :desc).each do |comment| %>
        <span class="u-user fa fa-user-circle" style="font-size:20px;"></span><span class="u-user"> # <%= comment.user.id %></span>
        <br/>
        <span class="u-user-message"><%= comment.message %></span>
        <hr/>
      <% end %>
    </div>
  </div>
  <div class="u-new-comment addcomment">
    <span class="fa fa-plus" style="font-size:23px;"></span>
    <span class="u-text">comment</span>
  </div>

<!-- image popup -->
  <div id="u-hide<%= @gram.id %>" class="u-hide" >
    <div class="u-grid-popup">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div class="u-image-popup">
        <%= image_tag @gram.image.url %>
      </div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>

  <script>
    $( ".addcomment" ).click(function() {
      $( "#AddComment" ).toggle();
    });
    $( "#u-show<%= @gram.id %>" ).click(function() {
      $( "#u-hide<%= @gram.id %>" ).show( "fade", 300 );
    });
    $( "#u-hide<%= @gram.id %>" ).click(function() {
      $( "#u-hide<%= @gram.id %>" ).hide( "fade", 300 );
    });
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Utterly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="u-columns">
      <div></div>
      <div>

<!-- header -->
        <div class="u-header">
          <div class="u-logo">
            <a href="/#">
              <%= render file: "app/assets/images/utterly_logo.svg" %>
            </a>
          </div>   

<!-- user -->
          <div class="u-sign">
            <% if  @gram.present? && current_user == @gram.user %>
              <span class="editpost">Edit</span> • <%= link_to 'Delete Post', gram_path, method: :delete, data: {confirm: 'Are you sure you want to delete is Post?'} %> • <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
            <% elsif current_user %>
              <span class="newpost">New Post</span> • <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
            <% else %>
              <span class="signup">Sign Up</span> • <span class="signin">Sign In</span>
            <% end %>

<!-- forms -->
            <div id="SignIn">
              <%= render template: "devise/sessions/new" %>
            </div>
            <div id="SignUp">
              <%= render template: "devise/registrations/new" %>
            </div>
            <div id="Forgot">
              <%= render template: "devise/passwords/new" %>
            </div>
            <div id="NewPost">
              <%= render template: "grams/new" %>
            </div>
            <% if current_user && @gram.present? %>
              <div id="EditPost">
                <%= render template: "grams/edit" %>
              </div>
            <% end %>
          </div>

<!-- show/hide -->
          <script>
            $( ".signin" ).click(function() {
              $( "#SignIn" ).toggle();
              $( "#SignUp" ).hide();
              $( "#Forgot" ).hide();
            });
            $( ".signup" ).click(function() {
              $( "#SignIn" ).hide();
              $( "#SignUp" ).toggle();
              $( "#Forgot" ).hide();
            });
            $( ".forgot" ).click(function() {
              $( "#SignIn" ).hide();
              $( "#SignUp" ).hide();
              $( "#Forgot" ).show();
            });
            $( ".newpost" ).click(function() {
              $( "#NewPost" ).toggle();

            });
            $( ".editpost" ).click(function() {
              $( "#EditPost" ).toggle();
            });
          </script>

<!-- alert -->
          <% if notice.present? %>
            <p class="notice"><%= notice %></p>
          <% end %>
          <% if alert.present? %>
            <p class="alert"><%= alert %></p>
          <% end %>
        </div>

<!-- content -->
        <div class="u-content">

<!-- yield -->
          <%= yield %>
        </div>

      </div>
      <div></div>
    </div>
  </body>
</html>